services:
  distribution:
    container_name: distribution
    image: ${IMAGE:-distribution/distribution:latest}
    restart: unless-stopped
    environment:
      CONFIG_DIR: ${CONFIG_DIR:-/configs}
      CONFIG_FILE: ${CONFIG_FILE:-/etc/distribution/config.yml}
    logging:
      driver: "json-file"
      options:
        max-size: 10m
        max-file: 3
    configs:
      - source: base-conf
        target: ${DISTRIBUTION_BASE_CONF_PATH:-/configs/base-conf.yaml}
    volumes:
      - distribution-hub:/var/lib/registry
    networks:
      - distribution-network

configs:
  base-conf:
    content: |
      version: 0.1
      log:
        accesslog:
          disabled: ${REGISTRY_LOG_ACCESSLOG_DISABLED:-false}
        level: ${REGISTRY_LOG_LEVEL:-warn}
        formatter: ${REGISTRY_LOG_FORMATTER:-json}
        fields:
          service: ${REGISTRY_LOG_FIELDS_SERVICE:-distribution}
          environment: ${REGISTRY_LOG_FIELDS_ENVIRONMENT:-production}
      storage:
          delete:
            enabled: ${REGISTRY_STORAGE_DELETE_ENABLED:-true}
          cache:
              blobdescriptor: ${REGISTRY_STORAGE_CACHE_BLOBDESCRIPTOR:-inmemory}
          filesystem:
              rootdirectory: /var/lib/registry
          maintenance:
              uploadpurging:
                  enabled: ${REGISTRY_STORAGE_MAINTENANCE_UPLOADPURGING_ENABLED:-false}
      http:
          addr: :5000
          headers:
              X-Content-Type-Options: [nosniff]
      health:
        storagedriver:
          enabled: true
          interval: 10s
          threshold: 3

volumes:
  distribution-hub:
    name: distribution-hub

networks:
  distribution-network:
    name: distribution-network